### PR TITLE
BugFix BOOST_STATIC_ASSERT

### PR DESCRIPTION
**Pull request by lxavier**
I had an error when compiling on kesch the release. It seems there is a typo (according to Carlos), here is the fix.

### CODE REVIEW

**Comment by lxavier** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Comment by clementval** [comment]
Jenkins build of serialbox should have failed as well ... no ?

**Comment by cosunae** [comment]
I dont know why jenkins it is not failing in kesch, the behaviour depends on the version of boost and the compiler. But in general this is a bug when using BOOST_STATIC_ASSERT, we need to use (( )).
And update the C2SM-RCM version.
So I will merge this.

**Pull request merged**
