### PR TITLE
Remove the removeintentin keyword

### PR DESCRIPTION
**Pull request by pspoerri**
This should fix issue #37 

As discussed with @clementval

### CODE REVIEW

**Comment by pspoerri** [comment]
We now force the removal of `INTENT(IN)` for every variable declared.

**Comment by pspoerri** [comment]
launch jenkins

**Comment by clementval** [comment]
Ok looks fine if the tests pass

**Comment by pspoerri** [comment]
Do we have tests that cover this? Or should I test this with another dataset?

**Comment by pspoerri** [comment]
launch jenkins

**Comment by clementval** [comment]
If you test the serialization unit tests it should be fine
I don't know if they are executed by jenkins ...

**Pull request merged**
