### PR TITLE
Fix issue created by PR #38

### PR DESCRIPTION
**Pull request by clementval**
PR #38 remove `intent(in)` for all variables but `pp_ser` will fail as it checks if all variable had `intent(in)`. Remove this check.

### CODE REVIEW

**Comment by clementval** [comment]
By the way, we really need some unit tests for `pp_ser.py` because now we don't check anything so a bug is really easy to make

**Comment by pspoerri** [comment]
Great thanks

**Comment by clementval** [comment]
Well as I use the repo as a dependency for the physics standalone, I needed it :-)

**Comment by pspoerri** [comment]
looks good to me. We need this change because we already changed the behavior of `pp_ser`.

**Pull request merged**
