### PR TITLE
Adapted the fortran CMakeLists.txt to allow compilation with PGI

### PR DESCRIPTION
**Pull request by pspoerri**

### CODE REVIEW

**Comment by pspoerri** [comment]
launch jenkins

**Comment by pspoerri** [comment]
launch jenkins

**Comment by clementval** [comment]
@pspoerri why is this assign to me ... ? I'll gladly do it but looks like you are doing something with this already ?

**Comment by pspoerri** [comment]
I just added you for review as I don't know the -cpp flag

**Comment by clementval** [comment]
@pspoerri ok nice ! I wanna try PGI with my standalone ... so it will make a good test case of serialbox PGI !

**Comment by pspoerri** [comment]
I already integrated the build with jenkins so it should be available once we merge this patch.

**Pull request merged**
